---
# Paybook que deve ser executado como root
- hosts: local
  remote_user: bodock
  become: true
  roles:
    - role: docker
      docker_install_compose: true
      docker_compose_version: "1.14.0"
