---
- name: Instala chave do repositório
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ spotify_repo_key }}"
    state: present
  become: true

- name: Configura repositório
  apt_repository:
    repo: "{{ spotify_repo_line }}"
    filename: "{{ spotify_repo_file }}"
    state: present
    update_cache: yes
  become: true

- name: Instala Spotify
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - spotify-client
    - libavcodec-extra
  become: true
