- name: Adiciona repo de icons
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - 'ppa:moka/daily'
  become: yes

- name: Instala pacotes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - arandr
    - xbacklight
    - lxappearance
    - thunar
    - numlockx
    - rofi
    - compton
    - arandr
    - i3blocks
    - pavucontrol
    - feh
    - moka-icon-theme
    - faba-icon-theme
    - faba-mono-icons
  become: yes

- include: fonts.yml

- name: Cria pasta de configração do i3 se necessário
  file:
    path: ~/.config/i3/
    recurse: true
    state: directory

- name: Copia configurações i3
  copy:
    src: files/i3.conf
    dest: ~/.config/i3/config

- name: Cria pasta de blocks se necessário
  file:
    path: /usr/share/i3blocks
    recurse: true
    state: directory
  become: yes

- name: Copia configurações do i3-blocks
  copy:
    src: files/i3blocks.conf
    dest: ~/.config/i3/i3blocks.conf

- name: Copia scripts do i3-blocks
  copy:
    src: "{{ item }}"
    dest: /usr/share/i3blocks/
    owner: root
    mode: 0755
  become: yes
  with_fileglob:
    - "files/blocks/*"

- name: Copia scripts de inicialização do i3
  file:
    src: files/scripts/"{{ item }}"
    dest: ~/scripts/"{{ item }}"
    mode: 0755
  with_items:
    - set_keys
