- name: Atualizar cache
  apt:
      update_cache: yes
      cache_valid_time: 3600
  become: yes

- name: Atualizar pacotes
  apt:
      upgrade: dist
  become: yes

- name: Adiciona repositórios
  apt_repository:
    repo: 'ppa:nathan-renniewaldock/flux'
    state: present
  become: yes

- name: Instala pacotes diários
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - aptitude
    - flake8
    - htop
    - lm-sensors
    - mplayer
    - vagrant
    - xclip
    - remmina
