#!/bin/bash

SCREEN_STATUS=$(xrandr -q)
if [[ $SCREEN_STATUS == *"HDMI-1-1 connected"* ]]
then
    xrandr --output eDP-1-1 --off --output VGA-1-1 --off --output HDMI-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
elif [[ $SCREEN_STATUS == *"VGA-1-1 connected"* ]]
then
    xrandr --output eDP-1-1 --off --output VGA-1-1 --primary --mode 1280x1024 --pos 0x0 --rotate normal --output HDMI-1-1 --off
else
    xrandr --output eDP-1-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output VGA-1-1 --off --output HDMI-1-1 --off
fi
